# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-02 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='rollno',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_title',
        ),
        migrations.AddField(
            model_name='album',
            name='dues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='song',
            name='extra',
            field=models.CharField(choices=[(b'chicken', b'CHICKEN'), (b'egg', b'EGG'), (b'butter', b'BUTTER'), (b'juice', b'JUICE')], default=b'chicken', max_length=7),
        ),
        migrations.AddField(
            model_name='song',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
